package: skh3
version: '0.2.0'
name: skh3
author: Falko Benthin
supportpage: https://github.com/aal4all/seminarkalendar

page:
  title: 'Seminare'
  perm: skh3[]
  icon: rex-icon fa-calendar
  subpages:
    seminare: 
      title: 'Seminare'
      perm: skh3[]
      icon: rex-icon fa-calendar-plus-o
    seminare_alt: 
      title: 'Alte Seminare'
      perm: skh3[]
      icon: rex-icon fa-calendar-plus-o
    personen: 
      title: 'Personen'
      perm: skh3[]
      icon: rex-icon fa-calendar-plus-o
    partner: 
      title: 'Partner'
      perm: skh3[]
      icon: rex-icon fa-calendar-plus-o
    geldgeber: 
      title: 'Geldgeber'
      perm: skh3[]
      icon: rex-icon fa-calendar-plus-o
    seminartyp: 
      title: 'Seminartypen'
      perm: skh3[]
      icon: rex-icon fa-calendar
requires:
    redaxo: '^5.8' 
    php:
        version: '>=7.1'
